# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: ov
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    cs-create: '!gh cs create --repo $(gh repo view --json nameWithOwner | jq -r .nameWithOwner)'
    repo-create: '!repo=$(basename $PWD) && gh repo create --public --source $PWD $repo && owner=$(gh repo view --json owner -q .owner.login) && gh api -X PUT repos/$owner/$repo/actions/permissions -F enabled=true'
    repo-url: '!url=$(gh repo view --json url --jq ".url" | tr -d " \n"); pbcopy <<< "$url" && echo "$url"'
    repo-events: '!gh api repos/$(gh repo view --json owner -q ".owner.login")/$(gh repo view --json name -q ".name")/events'
    myprs: '!id=$(set -e; gh pr list --state=all -L100 --author $(git config github.user) $@ | fzf | cut -f1); [ -n "$id" ] && gh pr view "$id" --web && echo "$id"'
    repo-create-private: '!repo=$(basename $PWD) && gh repo create --private --source $PWD $repo && owner=$(gh repo view --json owner -q .owner.login) && gh api -X PUT repos/$owner/$repo/actions/permissions -F enabled=true'
version: "1"
