[manager]
show_hidden = true

# https://github.com/yazi-rs/plugins/tree/main/git.yazi
[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"

[[manager.prepend_keymap]]
on = ["Y"]
run = "shell 'cat $0 | pbcopy' --confirm"
desc = "Copy file content to clipboard"
