#!/bin/bash
# Description: installation entrypoint for servers (linux).
#   - No GitHub tokens should be stored on server
#

cd "$(dirname "$0")/.." || exit 1

rsync --exclude-from="install/standard-exclude.txt" \
  --exclude-from="install/server-exclude.txt" \
  -av . ~

# musl to avoid glibc issues on some servers (pi)
curl https://mise.run | MISE_INSTALL_MUSL=1 sh

# this list was generated by chatgpt's ingestion of Brewfile; keep it up to date manually
sudo apt update
sudo apt install -y \
  git vim lynx rename wget ngrep iftop lftp httpie ncdu curl gawk jq sqlite3 zsh \
  entr prettyping less bc tree htop dnsutils moreutils qpdf \
  rsync watch iotop powertop mise libreadline-dev libffi-dev libyaml-dev \
  nmap

# erlang/ruby compile from source and are slow/unneeded on this devbox;
# elixir depends on erlang, so it must go too
mise settings set disable_tools '["erlang", "elixir", "ruby"]'

mise install -y

eval "$(mise activate zsh)"

cat <<EOF >~/.extra
alias dokku="docker exec -it dokku dokku"
alias dokku-shell="docker exec -it dokku bash -l"

eval "\$(fzf --zsh)"

# since we are removing the plugin which handles this
eval "\$(mise exec -- direnv hook zsh)"
EOF

# delete some zsh_plugins that are macos specific
sed -i '/zicompdef/d' ~/.zsh_plugins # assumes rg, etc which is not the same on servers :/
sed -i '/zsh-auto-notify/d' ~/.zsh_plugins
# sed -i '/fast-syntax-highlighting/d' ~/.zsh_plugins
# sed -i '/zsh-autosuggestions/d' ~/.zsh_plugins

sudo chsh -s "$(which zsh)" "$(whoami)"

git config --global --unset commit.gpgsign
git config --global credential.helper store

# if `python` doesn't exist, let's alias python3 to it if it exists
if ! command -v python &>/dev/null && command -v python3 &>/dev/null; then
  sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
fi

# cleaner output since this will be running inside ansible, or something similar
export ZINIT_COLORIZE=false

# run zinit to install all plugins
zsh -lc "source ~/.zshrc && zinit update --parallel"
