#!/bin/bash
# Description: installation entrypoint for servers (linux).
#   - No GitHub tokens should be stored on server
#

cd "$(dirname "$0")/.." || exit 1

rsync --exclude-from="install/standard-exclude.txt" \
  --exclude-from="install/server-exclude.txt" \
  -av . ~

install -Dm 0644 install/mise/linux.toml \
  "${HOME}/.config/mise/conf.d/linux.toml"

# forgit expects macOS-style pbcopy/pbpaste. Headless hosts have no display
# server, so relay clipboard data over OSC52 via osc. Executables (not aliases)
# so forgit works outside zsh too.
install -Dm 0755 install/linux/bin/pbcopy "${HOME}/.local/bin/pbcopy"
install -Dm 0755 install/linux/bin/pbpaste "${HOME}/.local/bin/pbpaste"

# mise → ~/.local/bin/mise (musl to avoid glibc issues on some servers/pis)
if [[ ! -x "${HOME}/.local/bin/mise" ]]; then
  curl https://mise.run | MISE_INSTALL_MUSL=1 sh
fi

# this list was generated by chatgpt's ingestion of Brewfile; keep it up to date manually
sudo apt update
sudo apt install -y \
  git vim lynx rename wget ngrep iftop lftp httpie ncdu curl gawk jq sqlite3 zsh \
  entr prettyping less bc tree htop dnsutils moreutils qpdf \
  rsync watch iotop powertop mise libreadline-dev libffi-dev libyaml-dev \
  nmap

export PATH="${HOME}/.local/bin:${PATH}"
eval "$(mise activate bash)"

# GitHub-backed mise tools require an already-resolvable token. `mise token`
# checks its configured sources (environment, OAuth cache, gh CLI, etc.)
# without exposing the token in installer output.
if [[ -z "$(mise token github --raw 2>/dev/null)" ]]; then
  echo "A GitHub token resolvable by mise is required (for example, MISE_GITHUB_TOKEN)." >&2
  exit 1
fi
mise self-update -y

# leave the clone: mise treats a `.config/mise/config.toml` relative to cwd as
# a local project config layered on top of the global one
cd "${HOME}" || exit 1

mise install -y

cat <<EOF >~/.extra
alias dokku="docker exec -it dokku dokku"
alias dokku-shell="docker exec -it dokku bash -l"

eval "\$(fzf --zsh)"

# since we are removing the plugin which handles this
eval "\$(mise exec -- direnv hook zsh)"
EOF

# delete some zsh_plugins that are macos specific
sed -i '/zicompdef/d' ~/.zsh_plugins # assumes rg, etc which is not the same on servers :/
sed -i '/zsh-auto-notify/d' ~/.zsh_plugins
# sed -i '/fast-syntax-highlighting/d' ~/.zsh_plugins
# sed -i '/zsh-autosuggestions/d' ~/.zsh_plugins

sudo chsh -s "$(which zsh)" "$(whoami)"

git config --global --unset commit.gpgsign
git config --global credential.helper store

# if `python` doesn't exist, let's alias python3 to it if it exists
if ! command -v python &>/dev/null && command -v python3 &>/dev/null; then
  sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
fi

# cleaner output since this will be running inside ansible, or something similar
export ZINIT_COLORIZE=false

# zinit's --no-pager path calls `cat`, but ~/.aliases maps that to bat. Give
# zsh non-TTY stdout so bat also disables its pager instead of spawning $PAGER
# (ov), which stops when zinit runs its parallel update job in the background.
zsh -lc "source ~/.zshrc && zinit update --parallel --no-pager" | /usr/bin/cat
